-----------------------------------
-- project:	Esquire
-- version:	2.0
-- Copyright (c) Miron 2000, 2001, 2025
--
-- file :	create/tree.all
-- desc:	biz Tree table
--
-----------------------------------
DROP TABLE ESQ_TREE
/
PROMPT Creating Table 'ESQ_TREE'
CREATE TABLE ESQ_TREE
 (TREE_PK VARCHAR2(33) DEFAULT 0 NOT NULL
 ,TREE_ET_PK NUMBER(5,0) DEFAULT 0 NOT NULL
 ,TREE_NAME VARCHAR2(50) NOT NULL
 ,TREE_DESC VARCHAR2(1024)
 ,TREE_TREE_PK_PARENT VARCHAR2(33)
 ,TREE_TREE_PK_LINK VARCHAR2(33)
 ,TREE_ACC_PK NUMBER(16,0)
 ,TREE_USR_PK NUMBER(16,0)
 ,TREE_ORG_PK NUMBER(16,0)
 ,TREE_LEVEL NUMBER(5,0)
 ,TREE_PATH VARCHAR2(2000)
 ,TREE_ENTITY_PK NUMBER(16,0)
 ,TREE_ENTITY_PATH VARCHAR2(2000)
)
/

COMMENT ON TABLE ESQ_TREE IS 'Business tree'
/
COMMENT ON COLUMN ESQ_TREE.TREE_PK IS 'Node primary key entityPk||entityType'
/
COMMENT ON COLUMN ESQ_TREE.TREE_ET_PK IS 'Entity type, reference to ESQ_ENTITY_TYPE'
/
COMMENT ON COLUMN ESQ_TREE.TREE_NAME IS 'Node name'
/
COMMENT ON COLUMN ESQ_TREE.TREE_DESC IS 'Node description'
/
COMMENT ON COLUMN ESQ_TREE.TREE_TREE_PK_PARENT IS 'Reference to parent node'
/
COMMENT ON COLUMN ESQ_TREE.TREE_TREE_PK_PARENT IS 'Reference to linked node'
/
COMMENT ON COLUMN ESQ_TREE.TREE_ACC_PK IS 'Reference to account (ESQ_ACCOUNT)'
/
COMMENT ON COLUMN ESQ_TREE.TREE_USR_PK IS 'Reference to user ((ESQ_USER)'
/
COMMENT ON COLUMN ESQ_TREE.TREE_ORG_PK IS 'Reference to organization unit  ((ESQ_ORG)'
/
COMMENT ON COLUMN ESQ_TREE.TREE_ENTITY_PK IS 'Entity PK represenging by node'
/
COMMENT ON COLUMN ESQ_TREE.TREE_ENTITY_PATH IS 'Entity Path represenging by node'
/
COMMENT ON COLUMN ESQ_TREE.TREE_ORG_PK IS 'location of the node as a path of parent'
/
COMMENT ON COLUMN ESQ_TREE.TREE_LEVEL IS 'Level node on tree starting with 0'
/


PROMPT Creating Primary Key on 'ESQ_TREE'
ALTER TABLE ESQ_TREE
 ADD (CONSTRAINT ESQ_TREE_PK PRIMARY KEY 
  (TREE_PK))
/


PROMPT Creating Foreign Keys on 'ESQ_TREE'
ALTER TABLE ESQ_TREE ADD (CONSTRAINT
 ESQ_TREE_TREE_PARENT_FK FOREIGN KEY 
  (TREE_TREE_PK_PARENT) REFERENCES ESQ_TREE
  (TREE_PK))
/
ALTER TABLE ESQ_TREE ADD (CONSTRAINT
 ESQ_TREE_TREE_LINK_FK FOREIGN KEY 
  (TREE_TREE_PK_LINK) REFERENCES ESQ_TREE
  (TREE_PK))
/
ALTER TABLE ESQ_TREE ADD (CONSTRAINT
 ESQ_TREE_ACC_FK FOREIGN KEY 
  (TREE_ACC_PK) REFERENCES ESQ_ACCOUNT
  (ACC_PK))
/
ALTER TABLE ESQ_TREE ADD (CONSTRAINT
 ESQ_TREE_USR_FK FOREIGN KEY 
  (TREE_USR_PK) REFERENCES ESQ_USER
  (USR_PK))
/
ALTER TABLE ESQ_TREE ADD (CONSTRAINT
 ESQ_TREE_ORG_FK FOREIGN KEY 
  (TREE_ORG_PK) REFERENCES ESQ_ORG
  (ORG_PK))
/

PROMPT Creating Index 'ESQ_TREE_TREE_PARENT_FK_I'
CREATE INDEX ESQ_TREE_TREE_PARENT_FK_I ON ESQ_TREE
  (TREE_TREE_PK_PARENT)
/

PROMPT Creating Index 'ESQ_TREE_TREE_LINK_FK_I'
CREATE INDEX ESQ_TREE_TREE_LINK_FK_I ON ESQ_TREE
  (TREE_TREE_PK_LINK)
/

PROMPT Creating Index 'ESQ_TREE_ACC_FK_I'
CREATE INDEX ESQ_TREE_ACC_FK_I ON ESQ_TREE
  (TREE_ACC_PK)
/

PROMPT Creating Index 'ESQ_TREE_USR_FK_I'
CREATE INDEX ESQ_TREE_USR_FK_I ON ESQ_TREE
  (TREE_USR_PK)
/

PROMPT Creating Index 'ESQ_TREE_ORG_FK_I'
CREATE INDEX ESQ_TREE_ORG_FK_I ON ESQ_TREE
  (TREE_ORG_PK)
/

