  DROP TABLE ESQ_TREE;
  DELETE FROM esq_account;
  DELETE FROM esq_usr_par;
  DELETE FROM esq_usr_prm;
  DELETE FROM esq_auth;
  DELETE FROM esq_user;
  DELETE FROM esq_org_par;
  DELETE FROM esq_org;
  DELETE FROM esq_permission;
  DELETE FROM esq_permission_type;
  DELETE FROM esq_parameter;
  DELETE FROM esq_entity_type;
  DELETE FROM esq_activity_type;
  COMMIT;
