-----------------------------------
-- project:	Esquire
-- version:	2.0
-- Copyright (c) Miron 2000, 2001, 2025
--
-- file :	fill/delete.sql
-- desc:	Delete fill data (Snowflake)
-----------------------------------

SELECT 'DROP TABLE ESQ_TREE' AS status;
DROP TABLE IF EXISTS ESQ_TREE;

SELECT 'Delete all data' AS status;
DELETE FROM ESQ_USR_PAR;
DELETE FROM ESQ_ORG_PAR;
DELETE FROM ESQ_USR_ROLE;
DELETE FROM ESQ_AUTH;
DELETE FROM ESQ_ACCOUNT;
DELETE FROM ESQ_ADDRESS;
DELETE FROM ESQ_PERSON;
DELETE FROM ESQ_USER;
DELETE FROM ESQ_ORG;
DELETE FROM ESQ_ROLE_ET;
DELETE FROM ESQ_ROLE_PRM;
DELETE FROM ESQ_ROLE;
DELETE FROM ESQ_PERMISSION;
DELETE FROM ESQ_PERMISSION_TYPE;
DELETE FROM ESQ_PARAMETER;
DELETE FROM ESQ_ENTITY_TYPE;
DELETE FROM ESQ_ACTIVITY_TYPE;

SELECT 'Done' AS status;
