-----------------------------------
-- project: Esquire
-- version: 2.0
-- Copyright (c) Miron 2000,2026
--
-- file :   fill/esq_role.sql
-- desc:    Fills esq_role table (Snowflake)
-----------------------------------

-----------------------------------
-- SYSADMIN
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      1, 'SYSADMIN', 980, 'System administrator role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (1, 30);
-- update, create, delete, security, accounting
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1,  0, 'N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 20, 'Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 30, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 32, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 34, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 36, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 50, 'Y,Y,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 52, 'Y,Y,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (1, 54, 'Y,Y,Y,N,Y,');

-----------------------------------
-- SUPERVIZOR
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      2, 'SUPERVIZOR', 980, 'Supervizor role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (2, 32);
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (2, 20, 'Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (2, 32, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (2, 34, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (2, 36, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (2, 50, 'Y,Y,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (2, 52, 'Y,Y,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (2, 54, 'Y,Y,Y,N,Y,');

-----------------------------------
-- MANAGER
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      3, 'MANAGER', 980, 'Office manager role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (3, 32);
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (3, 20, 'Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (3, 32, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (3, 34, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (3, 36, 'Y,Y,Y,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (3, 50, 'Y,Y,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (3, 52, 'Y,Y,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (3, 54, 'Y,Y,Y,N,Y,');

-----------------------------------
-- OPERATOR
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      4, 'OPERATOR', 980, 'Office operator role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (4, 32);
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (4, 20, 'N,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (4, 32, 'N,N,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (4, 34, 'N,Y,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (4, 36, 'N,Y,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (4, 50, 'N,Y,N,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (4, 52, 'N,Y,N,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (4, 54, 'Y,Y,Y,N,Y,');

-----------------------------------
-- SUPPORT
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      5, 'SUPPORT', 980, 'Customer support role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (5, 32);
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (5, 20, 'N,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (5, 30, 'N,N,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (5, 32, 'N,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (5, 34, 'N,Y,N,Y,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (5, 50, 'N,Y,N,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (5, 52, 'N,Y,N,N,N,');
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (5, 54, 'Y,Y,Y,N,Y,');

-----------------------------------
-- CLIENT
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      6, 'CLIENT', 980, 'Client role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (6, 34);
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (6, 54, 'N,N,N,N,Y,');

-----------------------------------
-- MERCHANT
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      7, 'MERCHANT', 980, 'Merchant role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (7, 36);

-----------------------------------
-- TREE
-----------------------------------
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      8, 'TREE', 982, 'Use of Esquire explorer api');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (8, 30);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (8, 32);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (8, 34);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (8, 36);
INSERT INTO ESQ_ROLE_PRM (RP_ROLE_PK, RP_PRM_PK, RP_ALLOWED_FLGS) VALUES (8, 100, 'Y,');

-- dummy roles
INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (      9, 'VAS-VAS', 982, 'Dummy role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (9, 30);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (9, 32);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (9, 34);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (9, 36);

INSERT INTO ESQ_ROLE (ROLE_PK, ROLE_NAME, ROLE_PT_PK, ROLE_DESC)
       VALUES        (     10, 'SAV-SAV', 982, 'Dummy role');
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (10, 30);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (10, 32);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (10, 34);
INSERT INTO ESQ_ROLE_ET (RT_ROLE_PK, RT_ET_PK) VALUES (10, 36);
