-----------------------------------
-- project:	Esquire
-- version:	2.0
-- Copyright (c) Miron 2000,2001,2025
--
-- file :	streams/all.sql
-- desc:	Snowflake Streams + Tasks for audit logging (replaces triggers)
--
-- NOTE: Snowflake does not support row-level triggers.
--       Instead, we use Streams (CDC) + Tasks (scheduled) to capture
--       changes and insert them into _LOG tables.
--       Tasks run every 1 minute when there is stream data available.
--
-- IMPORTANT: After running this script, you must resume tasks:
--   ALTER TASK ESQ_USER_LOG_TASK RESUME;
--   (repeat for each task)
-- Or run: !source streams/resume_tasks.sql
-----------------------------------
-- History:
-- 03/08/2026 Snowflake version created (replaces PostgreSQL triggers)

-- =====================================================================
-- Streams — capture changes on source tables
-- =====================================================================

SELECT 'Creating Streams' AS status;

CREATE OR REPLACE STREAM ESQ_USER_STREAM ON TABLE ESQ_USER APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_ADDRESS_STREAM ON TABLE ESQ_ADDRESS APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_BANK_INFO_STREAM ON TABLE ESQ_BANK_INFO APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_PERSON_STREAM ON TABLE ESQ_PERSON APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_AUTH_STREAM ON TABLE ESQ_AUTH APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_ORG_STREAM ON TABLE ESQ_ORG APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_ACCOUNT_STREAM ON TABLE ESQ_ACCOUNT APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_USR_PAR_STREAM ON TABLE ESQ_USR_PAR APPEND_ONLY = FALSE;
CREATE OR REPLACE STREAM ESQ_ORG_PAR_STREAM ON TABLE ESQ_ORG_PAR APPEND_ONLY = FALSE;

-- =====================================================================
-- Tasks — consume stream data and insert into _LOG tables
-- =====================================================================

SELECT 'Creating Tasks' AS status;

-- ESQ_USER -> ESQ_USER_LOG
CREATE OR REPLACE TASK ESQ_USER_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_USER_STREAM')
AS
  INSERT INTO ESQ_USER_LOG (USRL_ACTION, USRL_PK, USRL_ET_PK, USRL_NAME, USRL_PATH,
    USRL_REG_OPTION, USRL_ORG_PK, USRL_DELETED_FLG, USRL_DESC,
    USRL_CRL_ID, USRL_REQ_ID, USRL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    USR_PK, USR_ET_PK, USR_NAME, USR_PATH,
    USR_REG_OPTION, USR_ORG_PK, USR_DELETED_FLG, USR_DESC,
    USR_CRL_ID, USR_REQ_ID, USR_UID
  FROM ESQ_USER_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_ADDRESS -> ESQ_ADDRESS_LOG
CREATE OR REPLACE TASK ESQ_ADDRESS_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_ADDRESS_STREAM')
AS
  INSERT INTO ESQ_ADDRESS_LOG (ADL_ACTION, ADL_PK, ADL_ADDR, ADL_ADDR2, ADL_CITY,
    ADL_COMPANY, ADL_COUNTRY, ADL_DEPARTMENT, ADL_DESC, ADL_FAX,
    ADL_POSTAL_CODE, ADL_PROVINCE, ADL_TITLE, ADL_URL,
    ADL_CRL_ID, ADL_REQ_ID, ADL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    AD_PK, AD_ADDR, AD_ADDR2, AD_CITY,
    AD_COMPANY, AD_COUNTRY, AD_DEPARTMENT, AD_DESC, AD_FAX,
    AD_POSTAL_CODE, AD_PROVINCE, AD_TITLE, AD_URL,
    AD_CRL_ID, AD_REQ_ID, AD_UID
  FROM ESQ_ADDRESS_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_BANK_INFO -> ESQ_BANK_INFO_LOG
CREATE OR REPLACE TASK ESQ_BANK_INFO_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_BANK_INFO_STREAM')
AS
  INSERT INTO ESQ_BANK_INFO_LOG (BIL_ACTION, BIL_PK, BIL_NAME, BIL_BANK_NAME, BIL_BANK_CCY,
    BIL_ABA, BIL_SWIFT, BIL_ACCT, BIL_ADDR, BIL_CITY, BIL_PROVINCE, BIL_POSTAL_CODE,
    BIL_COUNTRY, BIL_SPEC_INSTR, BIL_BEN_NAME, BIL_BEN_BANK_NAME, BIL_BEN_BRANCH_NAME,
    BIL_BANK_NAME_I, BIL_ABA_I, BIL_SWIFT_I, BIL_CITY_I, BIL_COUNTRY_I,
    BIL_BEN_NAME_I, BIL_BEN_BANK_NAME_I, BIL_BEN_BRANCH_NAME_I,
    BIL_CRL_ID, BIL_REQ_ID, BIL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    BI_PK, BI_NAME, BI_BANK_NAME, BI_BANK_CCY,
    BI_ABA, BI_SWIFT, BI_ACCT, BI_ADDR, BI_CITY, BI_PROVINCE, BI_POSTAL_CODE,
    BI_COUNTRY, BI_SPEC_INSTR, BI_BEN_NAME, BI_BEN_BANK_NAME, BI_BEN_BRANCH_NAME,
    BI_BANK_NAME_I, BI_ABA_I, BI_SWIFT_I, BI_CITY_I, BI_COUNTRY_I,
    BI_BEN_NAME_I, BI_BEN_BANK_NAME_I, BI_BEN_BRANCH_NAME_I,
    BI_CRL_ID, BI_REQ_ID, BI_UID
  FROM ESQ_BANK_INFO_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_PERSON -> ESQ_PERSON_LOG
CREATE OR REPLACE TASK ESQ_PERSON_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_PERSON_STREAM')
AS
  INSERT INTO ESQ_PERSON_LOG (PEL_ACTION, PEL_USR_PK, PEL_KIND,
    PEL_FIRST_NAME, PEL_MIDDLE_NAME, PEL_LAST_NAME, PEL_TITLE, PEL_DOB,
    PEL_BIRTH_PLACE, PEL_SEX, PEL_TAX_ID, PEL_CITIZENSHIP, PEL_MAR_STATUS,
    PEL_PERSON_ID_TYPE, PEL_PERSON_ID_NUMBER, PEL_EMAIL, PEL_PHONE, PEL_PHONE2,
    PEL_BI_PK, PEL_AD_PK, PEL_AD_PK_BIZ,
    PEL_CRL_ID, PEL_REQ_ID, PEL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    PE_USR_PK, PE_KIND,
    PE_FIRST_NAME, PE_MIDDLE_NAME, PE_LAST_NAME, PE_TITLE, PE_DOB,
    PE_BIRTH_PLACE, PE_SEX, PE_TAX_ID, PE_CITIZENSHIP, PE_MAR_STATUS,
    PE_PERSON_ID_TYPE, PE_PERSON_ID_NUMBER, PE_EMAIL, PE_PHONE, PE_PHONE2,
    PE_BI_PK, PE_AD_PK, PE_AD_PK_BIZ,
    PE_CRL_ID, PE_REQ_ID, PE_UID
  FROM ESQ_PERSON_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_AUTH -> ESQ_AUTH_LOG
CREATE OR REPLACE TASK ESQ_AUTH_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_AUTH_STREAM')
AS
  INSERT INTO ESQ_AUTH_LOG (AUL_ACTION, AUL_USR_PK, AUL_CONNECT_FLG,
    AUL_LOGIN_ID, AUL_EMAIL, AUL_TFA_METHOD, AUL_FORCE_CHANGE_FLG,
    AUL_SECURITY_QUESTION, AUL_SECURITY_ANSWER,
    AUL_CRL_ID, AUL_REQ_ID, AUL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    AU_USR_PK, AU_CONNECT_FLG,
    AU_LOGIN_ID, AU_EMAIL, AU_TFA_METHOD, AU_FORCE_CHANGE_FLG,
    AU_SECURITY_QUESTION, AU_SECURITY_ANSWER,
    AU_CRL_ID, AU_REQ_ID, AU_UID
  FROM ESQ_AUTH_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_ORG -> ESQ_ORG_LOG
CREATE OR REPLACE TASK ESQ_ORG_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_ORG_STREAM')
AS
  INSERT INTO ESQ_ORG_LOG (ORGL_ACTION, ORGL_PK, ORGL_ET_PK, ORGL_NAME, ORGL_PATH,
    ORGL_FULL_NAME, ORGL_ORG_PK, ORGL_DESC,
    ORGL_CRL_ID, ORGL_REQ_ID, ORGL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    ORG_PK, ORG_ET_PK, ORG_NAME, ORG_PATH,
    ORG_FULL_NAME, ORG_ORG_PK, ORG_DESC,
    ORG_CRL_ID, ORG_REQ_ID, ORG_UID
  FROM ESQ_ORG_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_ACCOUNT -> ESQ_ACCOUNT_LOG
CREATE OR REPLACE TASK ESQ_ACCOUNT_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_ACCOUNT_STREAM')
AS
  INSERT INTO ESQ_ACCOUNT_LOG (ACCL_ACTION, ACCL_PK, ACCL_ET_PK, ACCL_PATH,
    ACCL_ID, ACCL_BALANCE, ACCL_CCY, ACCL_STATUS, ACCL_USR_PK, ACCL_DESC,
    ACCL_CRL_ID, ACCL_REQ_ID, ACCL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    ACC_PK, ACC_ET_PK, ACC_PATH,
    ACC_ID, ACC_BALANCE, ACC_CCY, ACC_STATUS, ACC_USR_PK, ACC_DESC,
    ACC_CRL_ID, ACC_REQ_ID, ACC_UID
  FROM ESQ_ACCOUNT_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_USR_PAR -> ESQ_USR_PAR_LOG
CREATE OR REPLACE TASK ESQ_USR_PAR_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_USR_PAR_STREAM')
AS
  INSERT INTO ESQ_USR_PAR_LOG (UPRL_ACTION, UPRL_USR_PK, UPRL_PAR_NAME, UPRL_PAR_ET_PK,
    UPRL_VALUE, UPRL_CRL_ID, UPRL_REQ_ID, UPRL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    UPR_USR_PK, UPR_PAR_NAME, UPR_PAR_ET_PK,
    UPR_VALUE, UPR_CRL_ID, UPR_REQ_ID, UPR_UID
  FROM ESQ_USR_PAR_STREAM
  WHERE METADATA$ACTION = 'INSERT';

-- ESQ_ORG_PAR -> ESQ_ORG_PAR_LOG
CREATE OR REPLACE TASK ESQ_ORG_PAR_LOG_TASK
  WAREHOUSE = ESQ_WH
  SCHEDULE = '1 MINUTE'
  WHEN SYSTEM$STREAM_HAS_DATA('ESQ_ORG_PAR_STREAM')
AS
  INSERT INTO ESQ_ORG_PAR_LOG (OPRL_ACTION, OPRL_ORG_PK, OPRL_PAR_NAME, OPRL_PAR_ET_PK,
    OPRL_VALUE, OPRL_CRL_ID, OPRL_REQ_ID, OPRL_UID)
  SELECT
    CASE WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = FALSE THEN 'I'
         WHEN METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE = TRUE  THEN 'U'
         WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = FALSE THEN 'D'
         ELSE 'U' END,
    OPR_ORG_PK, OPR_PAR_NAME, OPR_PAR_ET_PK,
    OPR_VALUE, OPR_CRL_ID, OPR_REQ_ID, OPR_UID
  FROM ESQ_ORG_PAR_STREAM
  WHERE METADATA$ACTION = 'INSERT';

SELECT 'Streams and Tasks created. Run resume_tasks.sql to activate.' AS status;
