-----------------------------------
-- Resume all audit log tasks
-- Run this after creating streams and tasks
-----------------------------------

ALTER TASK ESQ_USER_LOG_TASK RESUME;
ALTER TASK ESQ_ADDRESS_LOG_TASK RESUME;
ALTER TASK ESQ_BANK_INFO_LOG_TASK RESUME;
ALTER TASK ESQ_PERSON_LOG_TASK RESUME;
ALTER TASK ESQ_AUTH_LOG_TASK RESUME;
ALTER TASK ESQ_ORG_LOG_TASK RESUME;
ALTER TASK ESQ_ACCOUNT_LOG_TASK RESUME;
ALTER TASK ESQ_USR_PAR_LOG_TASK RESUME;
ALTER TASK ESQ_ORG_PAR_LOG_TASK RESUME;

SELECT 'All audit log tasks resumed' AS status;
