-----------------------------------
-- project:	Esquire
-- version:	2.0
-- Copyright (c) Miron 2000,2001,2025
--
-- file :	create/delete.sql
-- desc:	Deletion of DB objects (Snowflake)
--
-----------------------------------
-- History:
--
-- 01.08.2000			Created
-- 03.03.2001			Removes all objects
-- 03/08/2026       Snowflake version

SELECT 'Drop tables' AS status;

-- Drop streams first (depend on tables)
DROP STREAM IF EXISTS ESQ_USER_STREAM;
DROP STREAM IF EXISTS ESQ_ADDRESS_STREAM;
DROP STREAM IF EXISTS ESQ_BANK_INFO_STREAM;
DROP STREAM IF EXISTS ESQ_PERSON_STREAM;
DROP STREAM IF EXISTS ESQ_AUTH_STREAM;
DROP STREAM IF EXISTS ESQ_ORG_STREAM;
DROP STREAM IF EXISTS ESQ_ACCOUNT_STREAM;
DROP STREAM IF EXISTS ESQ_USR_PAR_STREAM;
DROP STREAM IF EXISTS ESQ_ORG_PAR_STREAM;

-- Drop tasks
DROP TASK IF EXISTS ESQ_USER_LOG_TASK;
DROP TASK IF EXISTS ESQ_ADDRESS_LOG_TASK;
DROP TASK IF EXISTS ESQ_BANK_INFO_LOG_TASK;
DROP TASK IF EXISTS ESQ_PERSON_LOG_TASK;
DROP TASK IF EXISTS ESQ_AUTH_LOG_TASK;
DROP TASK IF EXISTS ESQ_ORG_LOG_TASK;
DROP TASK IF EXISTS ESQ_ACCOUNT_LOG_TASK;
DROP TASK IF EXISTS ESQ_USR_PAR_LOG_TASK;
DROP TASK IF EXISTS ESQ_ORG_PAR_LOG_TASK;

-- Drop word-index procedures
DROP PROCEDURE IF EXISTS ESQ_WORD_INDEX_REINDEX();
DROP FUNCTION IF EXISTS ESQ_WORD_SEARCH(VARCHAR);

-- Drop tables
DROP TABLE IF EXISTS ESQ_TREE;
DROP TABLE IF EXISTS ESQ_WORD_INDEX_REF;
DROP TABLE IF EXISTS ESQ_WORD_INDEX;
DROP TABLE IF EXISTS ESQ_USR_PAR_LOG;
DROP TABLE IF EXISTS ESQ_ORG_PAR_LOG;
DROP TABLE IF EXISTS ESQ_USR_PAR;
DROP TABLE IF EXISTS ESQ_ORG_PAR;
DROP TABLE IF EXISTS ESQ_USR_ROLE;
DROP TABLE IF EXISTS ESQ_ROLE_ET;
DROP TABLE IF EXISTS ESQ_ROLE_PRM;
DROP TABLE IF EXISTS ESQ_ROLE;
DROP TABLE IF EXISTS ESQ_ACCT_TRANSACTION;
DROP TABLE IF EXISTS ESQ_ACCOUNT_LOG;
DROP TABLE IF EXISTS ESQ_ACCOUNT;
DROP TABLE IF EXISTS ESQ_AUTH_LOG;
DROP TABLE IF EXISTS ESQ_AUTH;
DROP TABLE IF EXISTS ESQ_PERSON_LOG;
DROP TABLE IF EXISTS ESQ_PERSON;
DROP TABLE IF EXISTS ESQ_BANK_INFO_LOG;
DROP TABLE IF EXISTS ESQ_BANK_INFO;
DROP TABLE IF EXISTS ESQ_ADDRESS_LOG;
DROP TABLE IF EXISTS ESQ_ADDRESS;
DROP TABLE IF EXISTS ESQ_USER_LOG;
DROP TABLE IF EXISTS ESQ_USER;
DROP TABLE IF EXISTS ESQ_ORG_LOG;
DROP TABLE IF EXISTS ESQ_ORG;
DROP TABLE IF EXISTS ESQ_PERMISSION;
DROP TABLE IF EXISTS ESQ_PERMISSION_TYPE;
DROP TABLE IF EXISTS ESQ_PARAMETER;
DROP TABLE IF EXISTS ESQ_ENTITY_TYPE;
DROP TABLE IF EXISTS ESQ_ACTIVITY_TYPE;

SELECT 'Drop sequences' AS status;

DROP SEQUENCE IF EXISTS ESQ_ENTITY_SEQ;
DROP SEQUENCE IF EXISTS ESQ_REF_SEQ;
DROP SEQUENCE IF EXISTS ESQ_ATR_SEQ;
