-----------------------------------
-- project:	Esquire
-- version:	2.0
-- Copyright (c) Miron 2000, 2001, 2025
--
-- file :	create/tables.cc
-- desc:	Check constraints
--
-- 01/14/2026 mir0n ESQ_USR_PRM table removed
-----------------------------------


PROMPT Creating Check Constraint on 'ESQ_USER'
ALTER TABLE ESQ_USER
 ADD (CONSTRAINT ESQ_USR_DELETED_FLG_CC CHECK (USR_DELETED_FLG IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'ESQ_AUTH'
ALTER TABLE ESQ_AUTH
 ADD (CONSTRAINT ESQ_AU_CONNECT_FLG_CC CHECK (AU_CONNECT_FLG IN ('Y','N')))
/
ALTER TABLE ESQ_AUTH
 ADD (CONSTRAINT ESQ_AU_TFA_METHOD_CC CHECK (AU_TFA_METHOD IN ('N','G')))
/

PROMPT Creating Check Constraint on 'ESQ_ACCOUNT'
ALTER TABLE ESQ_ACCOUNT
 ADD (CONSTRAINT ESQ_ACC_STATUS_CC CHECK (ACC_STATUS IN ('O','L','C')))
/

PROMPT Creating Check Constraint on 'ESQ_PERSON'
ALTER TABLE ESQ_PERSON
 ADD (CONSTRAINT ESQ_PE_KIND_CC CHECK (PE_KIND IN ('P','S','J')))
/

PROMPT Creating Check Constraint on 'ESQ_ENTITY_TYPE'
ALTER TABLE ESQ_ENTITY_TYPE
 ADD (CONSTRAINT ESQ_ET_ACC_FLG_CC CHECK (ET_ACC_FLG IN ('Y','N')))
/
ALTER TABLE ESQ_ENTITY_TYPE
 ADD (CONSTRAINT ESQ_ET_USR_FLG_CC CHECK (ET_USR_FLG IN ('Y','N')))
/
ALTER TABLE ESQ_ENTITY_TYPE
 ADD (CONSTRAINT ESQ_ET_ORG_FLG_CC CHECK (ET_ORG_FLG IN ('Y','N')))
/
ALTER TABLE ESQ_ENTITY_TYPE
 ADD (CONSTRAINT ESQ_ET_LINK_FLG_CC CHECK (ET_LINK_FLG IN ('Y','N')))
/

PROMPT Creating Check Constraint on 'ESQ_PARAMETER'
ALTER TABLE ESQ_PARAMETER
 ADD (CONSTRAINT ESQ_PAR_READWRITE_CC CHECK (PAR_READWRITE IN (0,1,3)))
/
ALTER TABLE ESQ_PARAMETER
 ADD (CONSTRAINT ESQ_PAR_TYPE_CC CHECK (PAR_TYPE IN ('string','flag','integer','number','datetime', 'tablist', 'tabstring', 'href', 'image' )))
/
ALTER TABLE ESQ_PARAMETER
 ADD (CONSTRAINT PAR_NULLABLE_FLG_CC CHECK (PAR_NULLABLE_FLG IN ('Y','N')))
/
