
CREATE USER esq2025 WITH PASSWORD 'q';

CREATE DATABASE esq2025
    WITH
    OWNER = esq2025
    ENCODING = 'UTF8'
    LOCALE_PROVIDER = 'libc'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;


GRANT ALL PRIVILEGES ON DATABASE esq2025 TO esq2025;



